version: '3.7'

services:
  
  nginx:
    image: nginx:${TAG}
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports: ['443:443']
    volumes: ['/home/twagner/data/html:/www']
    networks: ['docker-network']

  wordpress:
    image: wordpress:${TAG}
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    ports: ['9000:9000']
    #volumes: ['/home/twagner/data/html:/www']
    networks: ['docker-network']

networks:
  docker-network: {}
