version: '3.7'

services:
  
  nginx:
    image: nginx:${TAG}
    build: 
      context: ./bonus/nginx
      dockerfile: Dockerfile.bonus
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_healthy
      hugo:
          condition: service_healthy
    restart: always
    ports: ['443:443']
    volumes: ['wordpress_data:/var/www/wordpress']
    networks: ['inception_network']

  mariadb:
    image: mariadb:${TAG}
    build: 
      context: ./requirements/mariadb
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 20s
    volumes: ['db_data:/var/lib/mysql']
    networks: ['inception_network']

  wordpress:
    image: wordpress:${TAG}
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./bonus/wordpress
      dockerfile: Dockerfile.bonus
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment: 
      - WP_DB_HOST=${WORDPRESS_DB_HOST}
      - WP_DB_USER=${WORDPRESS_DB_USER}
      - WP_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WP_DB_NAME=${WORDPRESS_DB_NAME}
      - WP_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WP_DB_CHARSET=${WORDPRESS_DB_CHARSET}
      - WP_DB_COLLATE=${WORDPRESS_DB_COLLATE}
      - WP_SITE_URL=${WORDPRESS_SITE_URL}
      - WP_SITE_TITLE=${WORDPRESS_SITE_TITLE}
      - WP_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
    container_name: wordpress
    restart: always
    healthcheck:
      test: netstat -an | grep 9000 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      start_period: 10s
    volumes: ['wordpress_data:/var/www/wordpress']
    networks: ['inception_network']

  redis:
    image: redis:${TAG}
    build: 
      context: ./bonus/redis
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: redis
    restart: always
    networks: ['inception_network']

  ftp:
    image: ftp:${TAG}
    build: 
      context: ./bonus/ftp
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: ftp
    restart: always
    volumes: ['wordpress_data:/var/www/wordpress']
    networks: ['inception_network']

  adminer:
    image: adminer:${TAG}
    build: 
      context: ./bonus/adminer
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: adminer
    restart: always
    healthcheck:
      test: netstat -an | grep 9042 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 10s
      start_period: 10s
    networks: ['inception_network']
  
  hugo:
    image: hugo:${TAG}
    build: 
      context: ./bonus/hugo
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: hugo
    healthcheck:
      test: netstat -an | grep 1313 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;
      interval: 10s
      start_period: 10s
    restart: always
    networks: ['inception_network']
    
  cadvisor:
    image: cadvisor:${TAG}
    build: 
      context: ./bonus/cadvisor
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: cadvisor
    volumes: ['/var/run/docker.sock:/var/run/docker.sock:rw']
    restart: always
    networks: ['inception_network']

networks:
  inception_network:
    name: inception_network

volumes:
  wordpress_data:
    driver: local
    name: wordpress_data
    driver_opts:
      device: ${DATABIND}/wordpress
      type: volume
      o: bind
    
  db_data:
    driver: local
    name: db_data
    driver_opts:
      device: ${DATABIND}/db
      type: volume
      o: bind
