version: '3.7'

services:
  
  nginx:
    image: nginx:${TAG}
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports: ['443:443']
    volumes: ['/data/html:/www']
    networks: ['docker-network']

networks:
  docker-network: {}
