version: '3.7'

services:
  
  nginx:
    image: nginx:${TAG}
    build: 
      context: ./requirements/nginx
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    container_name: nginx
    depends_on:
      wordpress:
        condition: service_started
    restart: always
    ports: ['443:443']
    volumes: ['wordpress_data:/var/www/wordpress']
    networks: ['inception_network']

  mariadb:
    image: mariadb:${TAG}
    build: 
      context: ./requirements/mariadb
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    container_name: mariadb
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      start_period: 20s
    ports: ['3306:3306']
    volumes: ['db_data:/var/lib/mysql']
    networks: ['inception_network']

  wordpress:
    image: wordpress:${TAG}
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    environment: 
      - WP_DB_HOST=${WORDPRESS_DB_HOST}
      - WP_DB_USER=${WORDPRESS_DB_USER}
      - WP_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WP_DB_NAME=${WORDPRESS_DB_NAME}
      - WP_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
      - WP_DB_CHARSET=${WORDPRESS_DB_CHARSET}
      - WP_DB_COLLATE=${WORDPRESS_DB_COLLATE}
      - WP_SITE_URL=${WORDPRESS_SITE_URL}
      - WP_SITE_TITLE=${WORDPRESS_SITE_TITLE}
      - WP_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
    container_name: wordpress
    restart: always
    ports: ['9000:9000']
    volumes: ['wordpress_data:/var/www/wordpress']
    networks: ['inception_network']

networks:
  inception_network:
    driver: bridge
    name: inception_network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      device: ${DATABIND}/wordpress
      type: volume
      o: bind
    
  db_data:
    driver: local
    driver_opts:
      device: ${DATABIND}/db
      type: volume
      o: bind
