USE $WP_DB_NAME;

-- new non admin user
GRANT ALL ON $WP_DB_NAME TO '$WP_DB_USER'@'%' IDENTIFIED BY '$WP_DB_PQSSWORD';
GRANT ALL ON $WP_DB_NAME TO '$WP_DB_USER'@'localhost' IDENTIFIED BY '$WP_DB_PQSSWORD';
SET PASSWORD FOR '$WP_DB_USER'@'localhost'=PASSWORD('$WP_DB_PQSSWORD');

-- apply
FLUSH PRIVILEGES;